name: cognitive_data
description: A new Flutter package project.
version: 0.2.0
homepage:

environment:
  sdk: '>=2.18.0-216.0.dev <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  drift_dev: ^2.16.0
  build_runner: ^2.1.11
  test: ^1.21.1
  json_serializable: ^6.7.1
  # fake_cloud_firestore: ^2.1.0

flutter:
